services:
  lab:
    build: .
    image: wkhtmltopdf-stackoverflow-lab:latest
    volumes:
      - ./payloads:/lab/payloads:ro
      - ./output:/lab/output
    working_dir: /lab
    stdin_open: true
    tty: true
    # For GDB to work properly
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
